library(dplyr)
MechaCar_mpg <- read.csv(file='MechaCar_mpg.csv',check.names=F,stringsAsFactors = F)
head(MechaCar_mpg)
MechaCar_lm <- lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, MechaCar_mpg)
summary(MechaCar_lm)

SuspensionCoil <- read.csv(file='Suspension_Coil.csv',check.names = F,stringsAsFactors = F)
total_summary <- SuspensionCoil %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))
lot_summary <- SuspensionCoil %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))

t.test(SuspensionCoil$PSI, mu=1500)
Lot1Subset <- subset(SuspensionCoil, Manufacturing_Lot == 'Lot1')
Lot2Subset <- subset(SuspensionCoil, Manufacturing_Lot == 'Lot2')
Lot3Subset <- subset(SuspensionCoil, Manufacturing_Lot == 'Lot3')
t.test(Lot1Subset$PSI, mu=1500)
t.test(Lot2Subset$PSI, mu=1500)
t.test(Lot3Subset$PSI, mu=1500)
